{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.121.762.0 (23.09)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Sales\",\"Customer\",\"Item master\",\"Cities\",\"Sales Rep Master\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "8faeb2ef-3a80-4045-ad79-25279b6f4fa3",
        "fromColumn": "Order Date",
        "fromTable": "Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_186816bf-c70d-4c9a-bfc0-977abe402ea8"
      },
      {
        "name": "7c048e1c-d280-4f7c-baab-c05dffe9349a",
        "fromColumn": "Delivery Date",
        "fromTable": "Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0ac61cf5-b68a-481c-a061-556ceec3e178"
      },
      {
        "name": "1539206a-fcb5-47fc-9d9e-3851a6ac535b",
        "fromColumn": "Invoice Date",
        "fromTable": "Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4a4f0e56-aa62-4608-be47-529df90bd5e9"
      },
      {
        "name": "b9a816ab-1dc2-44c4-8249-ec6554c0f219",
        "fromColumn": "Item No",
        "fromTable": "Sales",
        "toColumn": "Item Number",
        "toTable": "Item master"
      },
      {
        "name": "33a8c283-f1f6-411f-aa08-136dd4a19ece",
        "fromColumn": "City Code",
        "fromTable": "Customer",
        "toColumn": "City Code",
        "toTable": "Cities"
      },
      {
        "name": "626f6b4e-74fc-4758-a83e-1f86c3c095dc",
        "fromColumn": "Rep ID",
        "fromTable": "Sales",
        "toColumn": "Sales Rep ID",
        "toTable": "Sales Rep Master"
      },
      {
        "name": "d1703cf6-d066-4784-9880-3d608e7c13ba",
        "fromColumn": "Customer No",
        "fromTable": "Sales",
        "toColumn": "Customer Number",
        "toTable": "Customer"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92d25db2-348c-48f5-b701-38f1e9e8f6bb",
            "sourceColumn": "PID",
            "summarizeBy": "count"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d5b262a-213f-43ee-8558-b48091254cc5",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Order No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "752b8733-72b7-4fb1-8979-639fa66cce01",
            "sourceColumn": "Order No",
            "summarizeBy": "sum"
          },
          {
            "name": "Item No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f3bcc23-4d2d-4bbb-916c-dd616579433e",
            "sourceColumn": "Item No",
            "summarizeBy": "none"
          },
          {
            "name": "Customer No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "435bfe03-7654-46f1-80d8-434d0bd4ef2c",
            "sourceColumn": "Customer No",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a7fe495f-21b4-4b2c-bd0d-f4ac5ec31953",
            "sourceColumn": "Invoice No",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "03e41878-c235-4d77-a230-91b1dd86b49a",
            "sourceColumn": "Order Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_186816bf-c70d-4c9a-bfc0-977abe402ea8"
                },
                "isDefault": true,
                "relationship": "8faeb2ef-3a80-4045-ad79-25279b6f4fa3"
              }
            ]
          },
          {
            "name": "Invoice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4e97cb62-b0b5-469a-93e8-158f087cf014",
            "sourceColumn": "Invoice Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4a4f0e56-aa62-4608-be47-529df90bd5e9"
                },
                "isDefault": true,
                "relationship": "1539206a-fcb5-47fc-9d9e-3851a6ac535b"
              }
            ]
          },
          {
            "name": "Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6ee2c697-9d3b-4428-8695-630d952c542e",
            "sourceColumn": "Delivery Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0ac61cf5-b68a-481c-a061-556ceec3e178"
                },
                "isDefault": true,
                "relationship": "7c048e1c-d280-4f7c-baab-c05dffe9349a"
              }
            ]
          },
          {
            "name": "Rep ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "475e5bc5-04df-492c-bd95-5976ced517a0",
            "sourceColumn": "Rep ID",
            "summarizeBy": "none"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e682b14-f677-4885-b4ae-030e4428bd8c",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "10296682-40af-402e-92da-ed628f76285e",
            "sourceColumn": "Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Margin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7628d134-4505-4a86-9f94-8a234c3aaf87",
            "sourceColumn": "Margin",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e30cf50f-c769-43c7-9aae-2f314fa17466",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Item Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd8aab35-bdec-40cd-a4e6-ab7d0f490b09",
            "sourceColumn": "Item Desc",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f77d5c48-5960-4834-920a-d63ba13e7148",
        "partitions": [
          {
            "name": "Sales-d188949f-1957-4993-a230-a5014f5ecbf9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Abhijit Gupta\\Documents\\Intership\\Sales Data\\Sales.xlsx\"), null, true),",
                "    Sales_Sheet = Source{[Item=\"Sales\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sales_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"PID\", Int64.Type}, {\"Company Name\", type text}, {\"Order No\", Int64.Type}, {\"Item No\", Int64.Type}, {\"Customer No\", Int64.Type}, {\"Invoice No\", Int64.Type}, {\"Order Date\", type date}, {\"Invoice Date\", type date}, {\"Delivery Date\", type date}, {\"Rep ID\", Int64.Type}, {\"Sales\", type number}, {\"Cost\", type number}, {\"Margin\", type number}, {\"Quantity\", Int64.Type}, {\"Item Desc\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_1da2a2b5-428f-4ff6-8b6f-110cbe733e2c",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ac6ea0be-c183-44d4-9118-2f07396ef441",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fb138d64-e443-4384-8c2f-66e423bb2f38",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1b71f2f4-37ef-4096-9e1b-c73b17b8317f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "28808640-9e79-4189-be1f-ae15afe79c3e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1020fe91-0c22-4144-845c-74605f039018",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "865a6ef3-e95f-4836-ac03-7d1fd0e40dcf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ec4604c6-afad-4b91-91e7-ae6ad131e95b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "400cc480-d3ae-4ce4-9eea-7fe329e9c579",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b75f20d5-c4c5-4822-839f-23cfdb7f325e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6030805e-aecb-44d9-9758-e3e1e34d877e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "55d39198-45c9-4114-b864-ff91bd9badfa",
                "ordinal": 3
              }
            ],
            "lineageTag": "e60b9ddb-5e8f-4425-a2b2-4fb24adbc556"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "1a1a5561-90a9-44e4-bca2-fc6656f4b2d2",
        "partitions": [
          {
            "name": "DateTableTemplate_1da2a2b5-428f-4ff6-8b6f-110cbe733e2c-a9e12e94-8e4e-4b8a-a8c3-500039566848",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_186816bf-c70d-4c9a-bfc0-977abe402ea8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "02ddb9af-8c2f-4fbc-867f-fb4f3e74d5cd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "38a1364b-7b7a-472f-adf9-207a786e2cc8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2993ea17-5b11-4aaa-bc75-c4f364e6e377",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2431d82e-3204-4336-a3d0-38cba4310257",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d6be70fa-1c5e-4276-a004-251ddf5d9443",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "06b67dbe-5c4e-4926-870f-031e3b439a30",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a078ff2-c221-402f-8d09-23cb0d1898a2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8e2a0f71-59cc-4b07-80a7-58344b595604",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4a159e72-3fc5-4f50-9a00-a26a7c355f38",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "331a81c4-c809-46cf-8643-93666f1eb0f7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "133d9ac7-79b2-4409-b10c-0859637e262e",
                "ordinal": 3
              }
            ],
            "lineageTag": "2648895d-013f-4486-af85-b2e80b74daec"
          }
        ],
        "isHidden": true,
        "lineageTag": "91eb02a6-846c-4e6d-8cee-2686a80e4684",
        "partitions": [
          {
            "name": "LocalDateTable_186816bf-c70d-4c9a-bfc0-977abe402ea8-4ecec569-639d-480f-bea8-da28d70a849b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sales'[Order Date])), 1, 1), Date(Year(MAX('Sales'[Order Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_0ac61cf5-b68a-481c-a061-556ceec3e178",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8c6968ff-2e2d-4e5d-b407-c5fc40477018",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "54aea53e-245a-463e-9a46-bedc5a504d82",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "41563de2-7c84-4ee7-82c9-84b6a28e2f79",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a7a42f5-a318-4648-ba7c-1228d2e1275a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "95f2de97-c88a-4a78-a816-d36b84c8104c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f160b0a2-9fb7-4608-bfcc-612f3261c0d3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ca85877b-71b0-4ed5-a405-1e791ad30a61",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a1b90cd5-c13c-4383-8909-5ab0ce8efd54",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "926dfa82-9048-4cfe-85fe-4301945b2d4b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "920e3951-dbaa-4e3b-ab66-aa5676f75670",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "14d5b76f-6e1d-4794-b60e-4e1c8744891c",
                "ordinal": 3
              }
            ],
            "lineageTag": "0f1c3fa7-727e-4e3c-bfb6-899bc49de0cd"
          }
        ],
        "isHidden": true,
        "lineageTag": "91d605fa-7ee0-41d6-8419-87b9f1c81039",
        "partitions": [
          {
            "name": "LocalDateTable_0ac61cf5-b68a-481c-a061-556ceec3e178-c4e1ff5a-5305-48ab-a577-381c0ab214d2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sales'[Delivery Date])), 1, 1), Date(Year(MAX('Sales'[Delivery Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "feb96a62-21aa-42df-b2bf-48c6feca3526",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c986bb95-b6ad-4244-8f86-48bcc950e139",
            "sourceColumn": "Customer Number",
            "summarizeBy": "none"
          },
          {
            "name": "City Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7790aef1-19a3-4676-b1b5-d575c0c84515",
            "sourceColumn": "City Code",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0236dd9e-3a01-4d19-96d1-96943fd5c3dd",
        "partitions": [
          {
            "name": "Customer-5b610efe-47e3-4d73-8841-74f027f93645",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Abhijit Gupta\\Documents\\Intership\\Sales Data\\Customers Master.xlsx\"), null, true),",
                "    Customer_Sheet = Source{[Item=\"Customer\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Customer_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Customer\", type text}, {\"Customer Number\", Int64.Type}, {\"City Code\", Int64.Type}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"Customer Number\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4a4f0e56-aa62-4608-be47-529df90bd5e9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b5956ade-0073-48b8-a62f-b9842c4909da",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8a2efa8e-9935-4beb-9ba0-eb5219012272",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ce5b2bf7-bcd0-4745-9899-023a23e203da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "63f88c6d-cd9f-4535-933d-aa67b28c4b97",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "942c11ad-9c0e-4e20-999e-3ff10a998346",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "feb9a3a4-1e0d-49be-9b35-e5c979953d8a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "03888996-c2ab-4c07-8866-676ecacb10ad",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7bc24bbc-1c15-49d0-900d-148ae2fb6394",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9c642800-7ccc-4e70-9f2a-c1bf495eff2e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "443104d5-3e55-491d-b3a8-3a6aa28d7fde",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ca4c4386-8837-45b9-ba53-d1bbbb42778c",
                "ordinal": 3
              }
            ],
            "lineageTag": "1c509c30-314d-47e2-8471-60d0951f8b6d"
          }
        ],
        "isHidden": true,
        "lineageTag": "b45518e2-0d89-482f-b9df-2636150063c2",
        "partitions": [
          {
            "name": "LocalDateTable_4a4f0e56-aa62-4608-be47-529df90bd5e9-66cc5653-22c5-4430-b1c2-723fe428cf5c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sales'[Invoice Date])), 1, 1), Date(Year(MAX('Sales'[Invoice Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Item master",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Item Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f6a65e29-1641-4b22-b5a8-9b709bb48ce5",
            "sourceColumn": "Item Number",
            "summarizeBy": "none"
          },
          {
            "name": "Product Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0215b81-d1ef-4c93-9d4e-b268182cd28a",
            "sourceColumn": "Product Group",
            "summarizeBy": "none"
          },
          {
            "name": "Product Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d56ffeb4-baf9-4b12-8de3-5ed1ffbcfb14",
            "sourceColumn": "Product Line",
            "summarizeBy": "none"
          },
          {
            "name": "Product Sub Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7c8717a-ae2d-4488-bd6f-1c39e9272e84",
            "sourceColumn": "Product Sub Group",
            "summarizeBy": "none"
          },
          {
            "name": "Product Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "324eacf8-4ce3-4e48-9fd3-c7ec56ac7f01",
            "sourceColumn": "Product Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f559ce79-e0b6-479f-8d2f-f5110a18bc4d",
        "partitions": [
          {
            "name": "Item master-43ca3e33-cbf6-4ef3-bd82-f56e26b9bc5b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Abhijit Gupta\\Documents\\Intership\\Sales Data\\Item Master.xlsx\"), null, true),",
                "    #\"Item master_Sheet\" = Source{[Item=\"Item master\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Item master_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Item Number\", Int64.Type}, {\"Product Group\", type text}, {\"Product Line\", type text}, {\"Product Sub Group\", type text}, {\"Product Type\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Cities",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "192e8260-977e-4098-8adb-f2a8126a580a",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "City Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a36234bf-e15e-4925-8236-0c1b9382578b",
            "sourceColumn": "City Code",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46cca934-5f66-4d30-8798-99c7eec49cb9",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e8ef417c-45db-46fe-84fc-f19eec1d577b",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f068d203-b1ca-4c03-b491-27293b773722",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fc29551-c582-4b79-98cd-f4ace2b57e60",
            "sourceColumn": "Desc",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0d43a475-f2ac-4f7a-86cb-1338e4f6fe4c",
        "partitions": [
          {
            "name": "Cities-0ee48fcd-670f-4e0e-b0f0-6162834f5930",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Abhijit Gupta\\Documents\\Intership\\Sales Data\\City Master.xlsx\"), null, true),",
                "    Cities_Sheet = Source{[Item=\"Cities\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Cities_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"City\", type text}, {\"City Code\", Int64.Type}, {\"Region\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}, {\"Desc\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Rep Master",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c7b91a3-d34e-4e6c-abb6-3cf5e3bb8a8c",
            "sourceColumn": "Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84ded9cf-0add-4a6a-ba83-6a9f5c4b4c04",
            "sourceColumn": "Manager Number",
            "summarizeBy": "none"
          },
          {
            "name": "Path",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec72d06f-8124-4441-890a-ad45b255b6f9",
            "sourceColumn": "Path",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Rep Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccca667a-24fb-41c9-ba29-eb4765d62002",
            "sourceColumn": "Sales Rep Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Rep Name1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9dff364-4aad-45f9-aab7-4e9a32cb2350",
            "sourceColumn": "Sales Rep Name1",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Rep Name2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bd4ff87-9f0c-4a97-895d-88d39310ee05",
            "sourceColumn": "Sales Rep Name2",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Rep Name3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "690eb885-31d9-4689-bda9-19b4b21e31ea",
            "sourceColumn": "Sales Rep Name3",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Rep ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "44b12ce0-1f70-4a04-b475-082bd2b4dd69",
            "sourceColumn": "Sales Rep ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cf12c3a7-c676-44c4-8667-63ce7ba6188b",
        "partitions": [
          {
            "name": "Sales Rep Master-393a33c2-a7e8-4723-b5d7-473e99a05935",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Abhijit Gupta\\Documents\\Intership\\Sales Data\\Sales Rep Master.csv\"),[Delimiter=\";\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Manager\", type text}, {\"Manager Number\", Int64.Type}, {\"Path\", type text}, {\"Sales Rep Name\", type text}, {\"Sales Rep Name1\", type text}, {\"Sales Rep Name2\", type text}, {\"Sales Rep Name3\", type text}, {\"Sales Rep ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}